[package]
name = "frank-release-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "frank-release"
path = "src/main.rs"

[dependencies]
clap.workspace = true
toml.workspace = true
toml_edit.workspace = true
sha2.workspace = true
anyhow.workspace = true
