use std::fs;
use std::path::Path;

/// `tauri_build` validates every configured resource even for `cargo check`
/// and `cargo test`. A clean checkout has no generated CLI sidecar yet, so
/// create clearly-dev-only placeholders to keep ordinary workspace commands
/// buildable. `scripts/prepare-sidecar.sh` always replaces both files before a
/// release bundle (and the Moon dev task does the same before launching Vite).
fn ensure_dev_resource(path: &Path, contents: &[u8], executable: bool) {
    if path.exists() {
        return;
    }
    if let Some(parent) = path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    if fs::write(path, contents).is_ok() && executable {
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = fs::set_permissions(path, fs::Permissions::from_mode(0o755));
        }
    }
}

fn main() {
    let packaging = Path::new(env!("CARGO_MANIFEST_DIR")).join("packaging");
    ensure_dev_resource(
        &packaging.join("frank"),
        b"#!/bin/sh\n# dev placeholder; run scripts/prepare-sidecar.sh for the real CLI\nexit 1\n",
        true,
    );
    ensure_dev_resource(
        &packaging.join("frank.exe"),
        b"Frank CLI sidecar is generated by scripts/prepare-sidecar.sh\r\n",
        false,
    );
    let target = std::env::var("TAURI_ENV_TARGET_TRIPLE")
        .or_else(|_| std::env::var("TARGET"))
        .unwrap_or_else(|_| "unknown-target".to_string());
    let windows = target.contains("windows");
    let sidecar_name = if windows {
        format!("frank-sidecar-{target}.exe")
    } else {
        format!("frank-sidecar-{target}")
    };
    ensure_dev_resource(
        &Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("binaries")
            .join(sidecar_name),
        if windows {
            b"Frank CLI sidecar is generated by scripts/prepare-sidecar.sh\r\n"
        } else {
            b"#!/bin/sh\n# dev placeholder; run scripts/prepare-sidecar.sh for the real CLI\nexit 1\n"
        },
        !windows,
    );
    tauri_build::build()
}
