[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
frank-pack = { path = "../crates/frank-pack", version = "0.2.5" }
frank-target = { path = "../crates/frank-target", version = "0.2.5" }
anyhow.workspace = true
sha2.workspace = true
clap.workspace = true
toml.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3"
