[package]
name = "frank-compress"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
regex.workspace = true
serde_json.workspace = true
frank-safeio = { path = "../frank-safeio", version = "0.2.3" }

[dev-dependencies]
proptest = "1"
tempfile = "3"
