//! Repo-maintenance tasks that aren't part of the shipped `frank` binary.
//!
//! `build-packs` compiles every pack under `packs/*/pack.toml` and writes a
//! `compiled.rs` next to it containing `&'static str` constants, which
//! `frank-cli` `include!`s. This runs ahead of time for the built-in pack
//! (committed, CI fails on drift) and gives the pack compiler a second real
//! caller besides `frank pack add`, so it's exercised as a library from day
//! one rather than only through a future runtime path.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command as ProcessCommand;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};

#[derive(Parser)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Compile every pack under packs/*/pack.toml into packs/<id>/compiled.rs.
    BuildPacks,
    /// Parse and validate every targets/*.toml manifest.
    LintTargets,
    /// Write dist/SHA256SUMS for every archive under dist/.
    Checksums,
    /// Package a release binary into dist/. Without --target this uses the
    /// host triple; CI passes an explicit target after cross-compiling it.
    Dist {
        #[arg(long)]
        target: Option<String>,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let root = repo_root()?;
    match cli.command {
        Command::BuildPacks => build_packs(&root),
        Command::LintTargets => lint_targets(&root),
        Command::Checksums => checksums(&root),
        Command::Dist { target } => dist(&root, target.as_deref()),
    }
}

fn repo_root() -> Result<PathBuf> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .context("CARGO_MANIFEST_DIR not set — run via `cargo run -p xtask`")?;
    Ok(PathBuf::from(manifest_dir)
        .parent()
        .context("xtask has no parent directory")?
        .to_path_buf())
}

fn build_packs(root: &Path) -> Result<()> {
    let packs_dir = root.join("packs");
    let mut built = 0usize;
    for entry in
        std::fs::read_dir(&packs_dir).with_context(|| format!("reading {}", packs_dir.display()))?
    {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let pack_dir = entry.path();
        if !pack_dir.join("pack.toml").is_file() {
            continue;
        }
        build_one_pack(&pack_dir)?;
        built += 1;
    }
    if built == 0 {
        anyhow::bail!("no packs found under {}", packs_dir.display());
    }
    println!("xtask build-packs: compiled {built} pack(s)");
    Ok(())
}

fn build_one_pack(pack_dir: &Path) -> Result<()> {
    let source = frank_pack::PackSource::load(pack_dir)
        .with_context(|| format!("loading pack at {}", pack_dir.display()))?;
    let compiled = frank_pack::compile(&source)
        .with_context(|| format!("compiling pack at {}", pack_dir.display()))?;

    let rust_src = emit_rust(&compiled);
    let out_path = pack_dir.join("compiled.rs");
    let changed = std::fs::read_to_string(&out_path).ok().as_deref() != Some(rust_src.as_str());
    std::fs::write(&out_path, &rust_src)
        .with_context(|| format!("writing {}", out_path.display()))?;

    for (id, level) in &compiled.levels {
        println!(
            "  {}/{id}: activation {}B, reinforce {}B",
            compiled.id,
            level.activation_prompt.len(),
            level.reinforce.len()
        );
    }
    if changed {
        println!(
            "  -> {} ({}changed)",
            out_path.display(),
            if changed { "" } else { "un" }
        );
    }
    Ok(())
}

/// Emit `compiled.rs`: plain Rust source with `&'static str` constants, so
/// the activation prompt is a `.rodata` slice at runtime — zero parse cost,
/// zero allocation. Compare to the archive's SessionStart hook, which does a
/// `readFileSync`, a frontmatter regex, and a 78-line filtering reduce on
/// every session start (`archive/src/hooks/caveman-activate.js:91-116`).
fn emit_rust(pack: &frank_pack::CompiledPack) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "// @generated by `cargo run -p xtask -- build-packs`. Do not edit by hand —"
    )
    .unwrap();
    writeln!(
        out,
        "// edit the pack.toml / fragment files next to this and regenerate."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub const PACK_ID: &str = {:?};", pack.id).unwrap();
    writeln!(out, "pub const PACK_VERSION: &str = {:?};", pack.version).unwrap();
    writeln!(
        out,
        "pub const DEFAULT_LEVEL: &str = {:?};",
        pack.default_level
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(out, "pub struct Level {{").unwrap();
    writeln!(out, "    pub id: &'static str,").unwrap();
    writeln!(out, "    pub title: Option<&'static str>,").unwrap();
    writeln!(out, "    pub aliases: &'static [&'static str],").unwrap();
    writeln!(out, "    pub activation_prompt: &'static str,").unwrap();
    writeln!(out, "    pub reinforce: &'static str,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "pub static LEVELS: &[Level] = &[").unwrap();
    for level in pack.levels.values() {
        writeln!(out, "    Level {{").unwrap();
        writeln!(out, "        id: {:?},", level.id).unwrap();
        writeln!(out, "        title: {},", opt_str(level.title.as_deref())).unwrap();
        writeln!(out, "        aliases: &[{}],", str_slice(&level.aliases)).unwrap();
        writeln!(
            out,
            "        activation_prompt: {:?},",
            level.activation_prompt
        )
        .unwrap();
        writeln!(out, "        reinforce: {:?},", level.reinforce).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "pub struct AliasEntry {{").unwrap();
    writeln!(out, "    pub alias: &'static str,").unwrap();
    writeln!(out, "    pub canonical: &'static str,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub static ALIASES: &[AliasEntry] = &[").unwrap();
    for (alias, canonical) in &pack.aliases {
        writeln!(
            out,
            "    AliasEntry {{ alias: {alias:?}, canonical: {canonical:?} }},"
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "pub struct Oneshot {{").unwrap();
    writeln!(out, "    pub id: &'static str,").unwrap();
    writeln!(out, "    pub prompt: &'static str,").unwrap();
    writeln!(out, "    pub restores_previous: bool,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub static ONESHOTS: &[Oneshot] = &[").unwrap();
    for o in pack.oneshots.values() {
        writeln!(out, "    Oneshot {{").unwrap();
        writeln!(out, "        id: {:?},", o.id).unwrap();
        writeln!(out, "        prompt: {:?},", o.prompt).unwrap();
        writeln!(out, "        restores_previous: {},", o.restores_previous).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "pub struct Activation {{").unwrap();
    writeln!(out, "    pub on: &'static [&'static str],").unwrap();
    writeln!(out, "    pub off: &'static [&'static str],").unwrap();
    writeln!(out, "    pub question_guard: Option<&'static str>,").unwrap();
    writeln!(out, "    pub command_prefix: Option<&'static str>,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub static ACTIVATION: Activation = Activation {{").unwrap();
    writeln!(out, "    on: &[{}],", str_slice(&pack.activation.on)).unwrap();
    writeln!(out, "    off: &[{}],", str_slice(&pack.activation.off)).unwrap();
    writeln!(
        out,
        "    question_guard: {},",
        opt_str(pack.activation.question_guard.as_deref())
    )
    .unwrap();
    writeln!(
        out,
        "    command_prefix: {},",
        opt_str(pack.activation.command_prefix.as_deref())
    )
    .unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "pub struct Reduction {{").unwrap();
    writeln!(out, "    pub level: &'static str,").unwrap();
    writeln!(out, "    pub mean: f64,").unwrap();
    writeln!(out, "    pub p25: Option<f64>,").unwrap();
    writeln!(out, "    pub p75: Option<f64>,").unwrap();
    writeln!(out, "    pub n: Option<u32>,").unwrap();
    writeln!(out, "    pub model: Option<&'static str>,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub static BENCHMARK: &[Reduction] = &[").unwrap();
    for (level, r) in &pack.benchmark {
        writeln!(out, "    Reduction {{").unwrap();
        writeln!(out, "        level: {level:?},").unwrap();
        writeln!(out, "        mean: {:?},", r.mean).unwrap();
        writeln!(out, "        p25: {},", opt_f64(r.p25)).unwrap();
        writeln!(out, "        p75: {},", opt_f64(r.p75)).unwrap();
        writeln!(out, "        n: {},", opt_u32(r.n)).unwrap();
        writeln!(out, "        model: {},", opt_str(r.model.as_deref())).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];").unwrap();

    out
}

fn opt_str(v: Option<&str>) -> String {
    match v {
        Some(s) => format!("Some({s:?})"),
        None => "None".to_string(),
    }
}

fn opt_f64(v: Option<f64>) -> String {
    match v {
        Some(n) => format!("Some({n:?})"),
        None => "None".to_string(),
    }
}

fn opt_u32(v: Option<u32>) -> String {
    match v {
        Some(n) => format!("Some({n})"),
        None => "None".to_string(),
    }
}

fn str_slice(items: &[String]) -> String {
    items
        .iter()
        .map(|s| format!("{s:?}"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// A manifest path field must expand under `$HOME` or be project-relative
/// (`./...`) — never an absolute path elsewhere on disk. This is enforced
/// here, at lint time, rather than at install time: a manifest that tried
/// to write outside those two roots should fail CI, not merely warn a
/// user at install.
fn check_path_scope(field: &str, raw: &str, errors: &mut Vec<String>) {
    if raw.starts_with("$HOME") || raw.starts_with("./") {
        return;
    }
    errors.push(format!(
        "{field} = \"{raw}\" must start with \"$HOME\" or \"./\""
    ));
}

fn lint_targets(root: &Path) -> Result<()> {
    let targets_dir = root.join("targets");
    if !targets_dir.is_dir() {
        println!("xtask lint-targets: no targets/ directory yet");
        return Ok(());
    }
    let mut checked = 0usize;
    let mut had_error = false;
    for entry in std::fs::read_dir(&targets_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }
        let raw = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?;

        let manifest: frank_target::manifest::TargetManifest = match toml::from_str(&raw) {
            Ok(m) => m,
            Err(e) => {
                eprintln!("FAIL {}: {e}", path.display());
                had_error = true;
                continue;
            }
        };

        let mut errors = Vec::new();
        for clause in &manifest.detect {
            if let Some(d) = &clause.dir {
                check_path_scope("detect.dir", d, &mut errors);
            }
            if let Some(f) = &clause.file {
                check_path_scope("detect.file", f, &mut errors);
            }
        }
        match &manifest.install {
            frank_target::manifest::InstallSpec::MarkdownBlock { markdown } => {
                check_path_scope("install.markdown.path", &markdown.path, &mut errors);
            }
            frank_target::manifest::InstallSpec::SettingsMerge { settings } => {
                check_path_scope("install.settings.path", &settings.path, &mut errors);
            }
            frank_target::manifest::InstallSpec::Files { file } => {
                for f in file {
                    check_path_scope("install.file.path", &f.path, &mut errors);
                }
            }
            frank_target::manifest::InstallSpec::Spawn { .. } => {}
        }
        if manifest.detect.is_empty() && !matches!(manifest.target.kind.as_str(), "native") {
            errors.push("no [[detect]] clauses — target can never be auto-detected".to_string());
        }

        if errors.is_empty() {
            println!(
                "OK   {} ({}, {}{})",
                manifest.target.id,
                manifest.target.kind,
                if manifest.target.verified {
                    "verified"
                } else {
                    "unverified"
                },
                if manifest.target.soft { ", soft" } else { "" }
            );
            checked += 1;
        } else {
            had_error = true;
            eprintln!("FAIL {} ({}):", manifest.target.id, path.display());
            for e in errors {
                eprintln!("  - {e}");
            }
        }
    }
    println!("xtask lint-targets: {checked} manifest(s) OK");
    if had_error {
        anyhow::bail!("one or more target manifests failed linting");
    }
    Ok(())
}

/// `rustc -vV`'s `host:` line — there's no `std` constant for "the triple
/// this binary happens to be running on" outside a build script, and a
/// build-script dependency isn't worth it for one xtask command.
fn host_triple() -> Result<String> {
    let out = ProcessCommand::new("rustc")
        .arg("-vV")
        .output()
        .context("running `rustc -vV`")?;
    if !out.status.success() {
        anyhow::bail!("`rustc -vV` exited with {:?}", out.status.code());
    }
    String::from_utf8_lossy(&out.stdout)
        .lines()
        .find_map(|l| l.strip_prefix("host: "))
        .map(str::to_string)
        .context("no `host:` line in `rustc -vV` output")
}

/// Packages a release binary for the host or an explicitly supplied target.
/// Cross-compilation itself remains a CI concern; this function only packages
/// a binary that was already built by Cargo.
fn dist(root: &Path, requested_target: Option<&str>) -> Result<()> {
    let triple = requested_target
        .map(str::to_string)
        .unwrap_or(host_triple()?);
    let binary_name = binary_name(&triple);
    let release_dir = match requested_target {
        Some(target) => root.join("target").join(target).join("release"),
        None => root.join("target/release"),
    };
    let release_bin = release_dir.join(binary_name);
    if !release_bin.exists() {
        anyhow::bail!(
            "release binary not found at {} — run `cargo build --release -p frank-cli` first",
            release_bin.display()
        );
    }

    let dist_dir = root.join("dist");
    std::fs::create_dir_all(&dist_dir)?;
    let archive_name = archive_name(&triple);
    let archive_path = dist_dir.join(&archive_name);

    let status = if triple.contains("windows") {
        package_zip(&release_bin, &archive_path)?
    } else {
        package_tar_gz(&release_dir, binary_name, &archive_path)?
    };
    if !status.success() {
        anyhow::bail!("packaging command exited with {:?}", status.code());
    }
    if !archive_path.is_file() {
        anyhow::bail!(
            "packaging command succeeded but did not create {}",
            archive_path.display()
        );
    }

    println!("xtask dist: wrote {}", archive_path.display());
    Ok(())
}

fn binary_name(triple: &str) -> &'static str {
    if triple.contains("windows") {
        "frank.exe"
    } else {
        "frank"
    }
}

fn archive_name(triple: &str) -> String {
    if triple.contains("windows") {
        format!("frank-{triple}.zip")
    } else {
        format!("frank-{triple}.tar.gz")
    }
}

fn package_tar_gz(
    release_dir: &Path,
    binary_name: &str,
    archive_path: &Path,
) -> Result<std::process::ExitStatus> {
    let mut command = ProcessCommand::new("tar");

    // A release archive should not change just because it was packaged again.
    // BSD tar (the default on macOS) stores the current time in gzip headers;
    // this option disables that timestamp. COPYFILE_DISABLE prevents macOS
    // resource-fork metadata from becoming an invisible archive input.
    #[cfg(target_os = "macos")]
    command.args(["--options", "gzip:!timestamp"]);

    // GNU tar accepts these flags and normalizes the member metadata. GZIP=-n
    // covers the compressor header on GNU tar versions that do not inherit
    // the normalized mtime from the archive format.
    #[cfg(target_os = "linux")]
    command.args([
        "--sort=name",
        "--mtime=@0",
        "--owner=0",
        "--group=0",
        "--numeric-owner",
    ]);

    let status = command
        .env("COPYFILE_DISABLE", "1")
        .env("GZIP", "-n")
        .args(["-czf"])
        .arg(archive_path)
        .arg("-C")
        .arg(release_dir)
        .arg(binary_name)
        .status()
        .context("running tar")?;
    Ok(status)
}

fn package_zip(binary_path: &Path, archive_path: &Path) -> Result<std::process::ExitStatus> {
    let script = format!(
        "Compress-Archive -LiteralPath {} -DestinationPath {} -Force",
        powershell_quote(binary_path),
        powershell_quote(archive_path),
    );
    ProcessCommand::new("powershell")
        .args(["-NoProfile", "-NonInteractive", "-Command", &script])
        .status()
        .context("running PowerShell Compress-Archive")
}

fn powershell_quote(path: &Path) -> String {
    format!("'{}'", path.display().to_string().replace('\'', "''"))
}

fn checksums(root: &Path) -> Result<()> {
    use sha2::{Digest, Sha256};

    let dist_dir = root.join("dist");
    if !dist_dir.is_dir() {
        anyhow::bail!(
            "{} does not exist — run `xtask dist` first",
            dist_dir.display()
        );
    }

    let mut lines = Vec::new();
    for entry in std::fs::read_dir(&dist_dir)? {
        let entry = entry?;
        let path = entry.path();
        let is_archive = path
            .file_name()
            .and_then(|n| n.to_str())
            .is_some_and(|n| n.ends_with(".tar.gz") || n.ends_with(".zip"));
        if !is_archive {
            continue;
        }
        if !path.is_file() {
            anyhow::bail!("archive path is not a regular file: {}", path.display());
        }
        let bytes = std::fs::read(&path)?;
        let digest = Sha256::digest(&bytes);
        let mut hex = String::with_capacity(64);
        for byte in digest {
            write!(&mut hex, "{byte:02x}").expect("writing into a String cannot fail");
        }
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        lines.push(format!("{hex}  {name}"));
    }
    lines.sort();

    if lines.is_empty() {
        anyhow::bail!(
            "no .tar.gz or .zip archives found in {}",
            dist_dir.display()
        );
    }

    let manifest_path = dist_dir.join("SHA256SUMS");
    std::fs::write(&manifest_path, lines.join("\n") + "\n")?;
    println!(
        "xtask checksums: wrote {} ({} entries)",
        manifest_path.display(),
        lines.len()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{archive_name, binary_name};

    #[test]
    fn unix_artifacts_use_tar_gzip_and_unix_binary_name() {
        assert_eq!(binary_name("aarch64-apple-darwin"), "frank");
        assert_eq!(
            archive_name("aarch64-apple-darwin"),
            "frank-aarch64-apple-darwin.tar.gz"
        );
    }

    #[test]
    fn windows_artifacts_use_zip_and_exe_binary_name() {
        assert_eq!(binary_name("x86_64-pc-windows-msvc"), "frank.exe");
        assert_eq!(
            archive_name("x86_64-pc-windows-msvc"),
            "frank-x86_64-pc-windows-msvc.zip"
        );
    }
}
