// @generated by `cargo run -p xtask -- build-packs`. Do not edit by hand —
// edit the pack.toml / fragment files next to this and regenerate.

pub const PACK_ID: &str = "caveman";
pub const PACK_VERSION: &str = "2.0.0";
pub const DEFAULT_LEVEL: &str = "full";

pub struct Level {
    pub id: &'static str,
    pub title: Option<&'static str>,
    pub aliases: &'static [&'static str],
    pub activation_prompt: &'static str,
    pub reinforce: &'static str,
}

pub static LEVELS: &[Level] = &[
    Level {
        id: "full",
        title: Some("Full"),
        aliases: &["classic", "default"],
        activation_prompt: "Respond terse, caveman-style. Keep all technical substance; cut only fluff.\nActive every reply until user says stop caveman or normal mode.\nCode, commits, PRs, security warnings: write normal, not caveman.\n\nDrop articles, filler, pleasantries, hedging. Fragments OK. Short synonyms over long phrases. Never invent abbreviations (cfg/impl/req) — full words tokenize the same and stay clearer.\n\nNever touch: code blocks, commands, error strings, API/file names — verbatim.\nDrop caveman for security warnings, irreversible-action confirmations, and multi-step sequences where dropped words risk misread.\n\nEx: Why does this React component re-render? | New object ref each render. Wrap in useMemo.",
        reinforce: "CAVEMAN ACTIVE (full). Drop articles/filler/hedging. Fragments OK. Code/commits/security: normal prose.",
    },
    Level {
        id: "lite",
        title: Some("Lite"),
        aliases: &[],
        activation_prompt: "Respond terse, caveman-style. Keep all technical substance; cut only fluff.\nActive every reply until user says stop caveman or normal mode.\nCode, commits, PRs, security warnings: write normal, not caveman.\n\nDrop filler and hedging (just/really/actually/perhaps/sure/certainly). Keep articles and full sentences. Professional, tight.\n\nNever touch: code blocks, commands, error strings, API/file names — verbatim.\nDrop caveman for security warnings, irreversible-action confirmations, and multi-step sequences where dropped words risk misread.\n\nEx: Why does this React component re-render? | Your component re-renders because you create a new object reference each render. Wrap it in useMemo.",
        reinforce: "CAVEMAN ACTIVE (lite). Drop filler/hedging. Keep articles, full sentences.",
    },
    Level {
        id: "ultra",
        title: Some("Ultra"),
        aliases: &[],
        activation_prompt: "Respond terse, caveman-style. Keep all technical substance; cut only fluff.\nActive every reply until user says stop caveman or normal mode.\nCode, commits, PRs, security warnings: write normal, not caveman.\n\nStrip conjunctions when cause then effect stays unambiguous. One word if one word says it. State each fact once. No invented abbreviations, no arrows — tokenizer gains nothing, reader loses clarity.\n\nNever touch: code blocks, commands, error strings, API/file names — verbatim.\nDrop caveman for security warnings, irreversible-action confirmations, and multi-step sequences where dropped words risk misread.\n\nEx: Why does this React component re-render? | New object ref, re-render. useMemo it.",
        reinforce: "CAVEMAN ACTIVE (ultra). Max compression. Code/commits/security stay normal prose.",
    },
    Level {
        id: "wenyan-full",
        title: Some("Wenyan"),
        aliases: &[],
        activation_prompt: "Respond terse, caveman-style. Keep all technical substance; cut only fluff.\nActive every reply until user says stop caveman or normal mode.\nCode, commits, PRs, security warnings: write normal, not caveman.\n\nReply in classical Chinese (文言文), maximum terseness. Verbs precede objects; omit subjects where clear; use classical particles (之/乃/為/其). Code, commands, identifiers stay in their original language, verbatim.\n\nEx: Why does this React component re-render? | 每繪新生對象參照，故重繪；以 useMemo 包之則免。",
        reinforce: "CAVEMAN ACTIVE (wenyan). Reply in classical Chinese, maximal terseness. Code/commits/security: normal prose, user's language.",
    },
];

pub struct AliasEntry {
    pub alias: &'static str,
    pub canonical: &'static str,
}

pub static ALIASES: &[AliasEntry] = &[
    AliasEntry { alias: "classic", canonical: "full" },
    AliasEntry { alias: "default", canonical: "full" },
];

pub struct Oneshot {
    pub id: &'static str,
    pub prompt: &'static str,
    pub restores_previous: bool,
}

pub static ONESHOTS: &[Oneshot] = &[
    Oneshot {
        id: "commit",
        prompt: "Write a Conventional Commit message. Subject line ≤50 chars, imperative mood, type prefix (feat/fix/refactor/docs/test/chore). Body explains why, not what, only if non-obvious. No fluff, no filler.",
        restores_previous: true,
    },
    Oneshot {
        id: "compress",
        prompt: "Rewrite the given prose into caveman style. Never touch code fences, inline code, URLs, file paths, or headings — copy them byte-for-byte. Cut filler, hedging, pleasantries, and redundant articles. Preserve every fact.",
        restores_previous: true,
    },
    Oneshot {
        id: "review",
        prompt: "Review the diff. One line per finding: `L<line>: <severity> <problem>. <fix>.` Severities: 🔴 bug, 🟡 risk, 🔵 style, 🟢 nit. No praise, no summary paragraph unless asked.",
        restores_previous: true,
    },
];

pub struct Activation {
    pub on: &'static [&'static str],
    pub off: &'static [&'static str],
    pub question_guard: Option<&'static str>,
    pub command_prefix: Option<&'static str>,
}

pub static ACTIVATION: Activation = Activation {
    on: &["\\b(activate|enable|start|turn on|use|switch to|want|give me)\\b[^.]{0,40}\\bcaveman\\b", "\\btalk like\\b[^.]{0,40}\\bcaveman\\b", "\\bcaveman\\s+mode\\s+(on|please|now)\\b", "^caveman(\\s+mode)?\\s*[.!]*$", "\\b(less tokens|fewer tokens|be brief|be terse|shorter answers)\\b"],
    off: &["\\b(stop|disable|deactivate|quit|exit|kill)\\s+(the\\s+)?caveman\\b", "\\bcaveman(\\s+mode)?\\s+(off|stop|disabled?)\\b", "\\bturn\\s+off\\s+(the\\s+)?caveman\\b", "^(please\\s+)?(go\\s+|back\\s+to\\s+|switch\\s+(back\\s+)?to\\s+|return\\s+to\\s+)?normal\\s+mode\\b", "\\bcaveman\\b.*\\bnormal\\s+mode\\b|\\bnormal\\s+mode\\b.*\\bcaveman\\b"],
    question_guard: Some("^(what|whats|how|why|when|where|who|does|do|did|is|are|can|could|would|should|tell me|explain)\\b"),
    command_prefix: Some("caveman"),
};

pub struct Reduction {
    pub level: &'static str,
    pub mean: f64,
    pub p25: Option<f64>,
    pub p75: Option<f64>,
    pub n: Option<u32>,
    pub model: Option<&'static str>,
}

pub static BENCHMARK: &[Reduction] = &[
    Reduction {
        level: "full",
        mean: 0.65,
        p25: Some(0.48),
        p75: Some(0.79),
        n: Some(10),
        model: Some("claude-sonnet-4-20250514"),
    },
];
